<完成物要件>  
・担当者ごとのテーブルは新シートに追加  
　- 担当者シートのシート名は「名前_売上金額合計」  
・空白セルがあるデータは無効として除外

In [ ]:
import pandas as pd
import openpyxl as px

#親テーブル作成
col_list=[]
wb=px.load_workbook("売上一覧(改).xlsx")
ws=wb.worksheets[0]

for col in range(2,10):
    col_list.append(ws.cell(3,col).value) #項目名リスト

df=pd.read_excel("売上一覧(改).xlsx",sheet_name=0)
df=df.iloc[2:102,1:9]
df=df.set_axis(col_list,axis=1) #項目名を設定

df.isnull()
nul_list=[]
for i in range(df.shape[0]):
    if df.isnull().any(axis=1).iloc[i]==True:
        nul_list.append(i)
df=df.drop(df.index[nul_list]) #空白セルの削除

df_oya=df.reset_index(drop=True) #インデックスをリセット

#子シート作成
name=df_oya["担当者"].unique()
with pd.ExcelWriter(r"C:\Users\mkuno5808\Desktop\基礎\Udemy\Python\Excel編\4章\売上一覧(改) - コピー.xlsx",mode="a") as writer:
    for nm in name:
        df_ko=df_oya[df_oya["担当者"]==nm]
        SUM=df_ko["売上金額"].sum()
        df_ko.to_excel(writer,sheet_name=nm+"_"+str(SUM),index=False)

In [4]:
import pandas as pd
import openpyxl as px

#親テーブル作成
df=pd.read_excel("売上一覧(改).xlsx",sheet_name=0,header=2)
last_row=0
for c in reversed(range(len(df))):
    if df.isnull().iloc[c,4]==False:
        last_row=c
        break

df=df.iloc[:last_row+1,1:9]
df=df.dropna()
df

name=df_oya["担当者"].unique()
with pd.ExcelWriter(r"C:\Users\mkuno5808\Desktop\基礎\Udemy\Python\Excel編\4章\売上一覧(改) - コピー.xlsx",mode="a") as writer:
    for nm in name:
        df_ko=df_oya[df_oya["担当者"]==nm]
        SUM=df_ko["売上金額"].sum()
        df_ko.to_excel(writer,sheet_name=nm+"_"+str(SUM),index=False)

      No.        取引日       取引先 担当者    商品名      単価   個数    売上金額
0     1.0 2022-04-01  テスト１株式会社  田中  キーボード    6000  1.0    6000
1     2.0 2022-04-02  テスト２株式会社  佐藤  タブレット   50000  1.0   50000
3     4.0 2022-04-04  テスト３株式会社  鈴木  キーボード    6000  2.0   12000
4     5.0 2022-04-05  テスト１株式会社  田中  タブレット   50000  4.0  200000
5     6.0 2022-04-06  テスト１株式会社  鈴木    マウス    1500  4.0    6000
..    ...        ...       ...  ..    ...     ...  ...     ...
94   95.0 2022-07-04  テスト３株式会社  鈴木    マウス    1500  2.0    3000
95   96.0 2022-07-05  テスト１株式会社  佐藤  キーボード    6000  2.0   12000
97   98.0 2022-07-07  テスト３株式会社  鈴木  キーボード    6000  5.0   30000
98   99.0 2022-07-08  テスト２株式会社  佐藤    マウス    1500  2.0    3000
99  100.0 2022-07-09  テスト１株式会社  佐藤     PC  100000  3.0  300000

[95 rows x 8 columns]